name: Deploy Cloud Forensic Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt \
            --target backend/.python_packages/lib/site-packages

      - name: Verify backend
        run: |
          test -f backend/app/main.py
          test -f backend/requirements.txt
          test -f backend/.python_packages/lib/site-packages/uvicorn/__init__.py
          echo "Backend and Uvicorn verified"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2E392625933148F29B27D490C5B2D60B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F262895AC5B049228F6250A8BF5CA04C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BCC67289DF834CC697DA1F9FFD957730 }}

      - name: Configure Azure App Service
        run: |
          az webapp config set \
            --resource-group Forensic-Demo-RG \
            --name forensic-platform-api \
            --startup-file "python main.py"

      - name: Deploy backend to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: forensic-platform-api
          slot-name: Production
          package: ./backend
